spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "3.0"

cards:
  message: "Welcome to cards related prod APIs "
  contactDetails:
    name: "Mudit - Client"
    email: "muditClient@gmail.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932