spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to cards related QA APIs "
  contactDetails:
    name: "Mudit - QA"
    email: "muditTester@gmail.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932